In [15]:
import numpy as np

### [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)

In [16]:
rng = np.random.default_rng(42) # https://numpy.org/doc/stable/reference/random/generator.html

rng.integers(1, 11, size=5) # https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html
rng.random(size=5) # https://numpy.org/doc/stable/reference/random/generated/numpy
rng.choice(['apple', 'banana', 'cherry', 'pear'], size=3) # https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html

array(['pear', 'cherry', 'apple'], dtype='<U6')

### [Masked arrays operations](https://numpy.org/doc/stable/reference/routines.ma.html)

In [17]:
vector = np.array([1, 2, 3, 4, 5])

np.mean(vector) # https://numpy.org/doc/stable/reference/generated/numpy.ma.mean.html
np.median(vector) # https://numpy.org/doc/stable/reference/generated/numpy.ma.median.html
np.std(vector) # https://numpy.org/doc/stable/reference/generated/numpy.std.html

np.float64(1.4142135623730951)

### [Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [18]:
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector_zero = np.zeros(3) # https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
matrix_identity = np.eye(3) # https://numpy.org/doc/stable/reference/generated/numpy.eye.html
matrix_ones = np.ones((3, 3)) # https://numpy.org/doc/stable/reference/generated/numpy.ones.html

matrix_ones + 1 # https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__add__.html

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [19]:
matrix[:, 0] # First column -> all rows, first column

array([1, 4, 7])

In [20]:
matrix[2, :] # Third row -> third row, all columns

array([7, 8, 9])

#### [Reshape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html)

In [21]:
matrix_4x3= np.array([[1, 4, 5], [10, 13, 9], [10, 13, 9], [10, 8, 5]])
matrix_4x3.reshape(2, -1) # 2 Rows, -1 means infer the number of columns

array([[ 1,  4,  5, 10, 13,  9],
       [10, 13,  9, 10,  8,  5]])

In [22]:
matrix_4x3.reshape(-1, 2) # 2 Columns, -1 means infer the number of rows

array([[ 1,  4],
       [ 5, 10],
       [13,  9],
       [10, 13],
       [ 9, 10],
       [ 8,  5]])

#### [Searching](https://numpy.org/doc/stable/reference/routines.sort.html)

In [23]:
argmax_row = np.argmax(matrix_4x3, axis=1) # https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
argmax_row

array([2, 1, 1, 0])

In [24]:
max_row = np.max(matrix_4x3, axis=1) # https://numpy.org/doc/stable/reference/generated/numpy.max.html
max_row

array([ 5, 13, 13, 10])

In [25]:
my_matrix = np.array([[1, 4, 5], [10, 13, 9], [10, 8, 5]])

In [26]:
every_second_row = my_matrix[::2, :] # https://numpy.org/doc/stable/user/basics.indexing.html
every_second_row

array([[ 1,  4,  5],
       [10,  8,  5]])

In [27]:
every_second_column_reversed = my_matrix[:, ::-2]
every_second_column_reversed

array([[ 5,  1],
       [ 9, 10],
       [ 5, 10]])

In [28]:
even_numbers = my_matrix[my_matrix % 2 == 0] # https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__mod__.html
even_numbers

array([ 4, 10, 10,  8])

In [29]:
odd_numbers = my_matrix[my_matrix % 2 == 1]
odd_numbers

array([ 1,  5, 13,  9,  5])